environment:
  DUMP_URL: https://dumps.wikimedia.org/dewiktionary/20161120/dewiktionary-20161120-pages-articles.xml.bz2
  DOWNLOAD_PATH: C:\dewiktionary-20161120-pages-articles.xml.bz2
  

before_build:
  - nuget restore
  
install:
  - if not exist %DOWNLOAD_PATH% appveyor DownloadFile "%DUMP_URL%" -FileName %DOWNLOAD_PATH%
  
  - 7z e %DOWNLOAD_PATH% -oC:\
  
  - DEL /Q "C:\projects\iwnlp\IWNLP.ParserTest\App.config"
  - rename "C:\projects\iwnlp\IWNLP.ParserTest\App.AppVeyor.config" "App.config"
  
cache:
  - C:\dewiktionary-20161120-pages-articles.xml.bz2
